Diploma/Controllers/FileLoaderController.cs
using DevExpress.DashboardAspNetCore;
using DevExpress.DashboardCommon;
using DevExpress.DashboardWeb;
using Diploma.Models;
using Microsoft.AspNetCore.Mvc;

namespace Diploma.Controllers
{
    public class FileLoaderController : Controller
    {
        public FileLoaderController(IFileLoader loader, DashboardConfigurator configurator, IConfiguration configuration)
        {
            _loader = loader;
            _configurator = configurator;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            foreach (var file in _loader.GetFileList())
            {
                Console.WriteLine(file);
            }
            _fileDataViewModel.FileNames = _loader.GetFileList();
            return View(_fileDataViewModel);
        }

        [HttpPost]
        public IActionResult UploadFiles(IFormFileCollection uploadingFiles)
        {
            foreach (var file in uploadingFiles)
            {
                _loader.UploadFile(file);
            }
            _fileDataViewModel.FileNames = _loader.GetFileList();
            return View("Index", _fileDataViewModel);
        }

        public IActionResult DeleteFile(string fileName)
        {
            _loader.DeleteFile(fileName);
            _fileDataViewModel.FileNames = _loader.GetFileList();
            return View("Index", _fileDataViewModel);
        }

        public IActionResult Analyze(string fileName)
        {
            _loader.ConvertToJson(fileName);
            _fileDataViewModel.FileNames = _loader.GetFileList();
            return View("Index", _fileDataViewModel);
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        [HttpPost]
        public IActionResult File(string DataSourceFileName)
        {
            string json = _loader.GetFile(DataSourceFileName);
            if (json != "File not exist!")
            {
                DataSourceInMemoryStorage dataSourceStorage = new DataSourceInMemoryStorage();
                DashboardJsonDataSource jsonDataSourceString = new CustomDataSource($"JSON Data Source ({DataSourceFileName})", json);
                dataSourceStorage.RegisterDataSource(DataSourceFileName, jsonDataSourceString.SaveToXml());
                _configurator.SetDataSourceStorage(dataSourceStorage);
                _configurator.SetConnectionStringsProvider(new DashboardConnectionStringsProvider(_configuration));
            }
            else
            {
                Console.WriteLine("File not exist");
            }
            return RedirectToAction("Dashboard");
        }

        [HttpPost]
        public IActionResult ReturnToMenu(string Result)
        {
            return View("Index", _fileDataViewModel);
        }

        private FileDataViewModel _fileDataViewModel = new();

        private IFileLoader _loader;

        private DashboardConfigurator _configurator;

        private IConfiguration _configuration;
    }
}

Diploma/Views/Shared/_Layout.cshtml
@using DevExpress.AspNetCore
@using DevExpress.DashboardWeb
@using DevExpress.DashboardAspNetCore

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diploma</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Diploma.styles.css" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" />
    <script src="~/js/site.min.js"></script>

    <script type="text/html" id="dx-save-data-source-form">
        <div>Json Data Source:</div>
        <div style="margin: 10px 0" data-bind="dxTextBox: { value: newName }"></div>
        <div data-bind="dxButton: { text: 'Save', onClick: saveAs }"></div>
    </script>

    <script type="text/javascript">
        function onBeforeRender(sender) {
            var dashboardControl = sender;
            dashboardControl.registerExtension(new SaveDataSourceExtension(dashboardControl));
            dashboardControl.registerExtension(new RedirectToMenuExtension(dashboardControl));
        }
    </script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Diploma</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileLoader" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileLoader" asp-action="Dashboard">Dashboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <script type="text/javascript" src="~/js/SaveDataSourceExtension.js"></script>
            <script type="text/javascript" src="~/js/RedirectToMenuExtension.js"></script>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Diploma - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>